name: Update GitHub Followers

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq (JSON Parser)
        run: sudo apt-get install -y jq

      - name: Fetch Followers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/yashKappa/followers?per_page=10" > followers.json
          echo '<p align="center">' > followers.md
          cat followers.json | jq -r '.[] | "<a href=\"" + .html_url + "\"><img src=\"" + .avatar_url + "\" width=\"50px\" style=\"border-radius: 50%; margin: 5px;\"><br>" + .login + "</a>&nbsp;&nbsp;"' >> followers.md
          echo '</p>' >> followers.md

      - name: Update README
        run: |
          sed -i '/<!-- FOLLOWER_SECTION:start -->/,/<!-- FOLLOWER_SECTION:end -->/c\<!-- FOLLOWER_SECTION:start -->\n'$(cat followers.md)'\n<!-- FOLLOWER_SECTION:end -->' README.md

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated followers list" || echo "No changes to commit"
          git push || echo "No changes to push"
