name: Update Followers List

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual execution

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full history to prevent merge issues

      - name: Fetch Followers List with Profile Images
        run: |
          FOLLOWERS=$(curl -s https://api.github.com/users/yashKappa/followers?per_page=100)
          
          echo "<!-- FOLLOWERS_SECTION:start -->" > followers.md
          echo "" >> followers.md
          echo "<h2>🚀 My Followers</h2>" >> followers.md
          echo "" >> followers.md
          echo "<p align=\"left\">" >> followers.md

          echo "$FOLLOWERS" | jq -r '.[] | "<a href=\"https://github.com/\(.login)\"><img src=\"\(.avatar_url)&s=100\" width=\"80\" height=\"80\" style=\"border-radius: 50%; margin: 5px;\"></a>"' >> followers.md

          echo "</p>" >> followers.md
          echo "" >> followers.md
          echo "<!-- FOLLOWERS_SECTION:end -->" >> followers.md

      - name: Update README.md
        run: |
          awk '/<!-- FOLLOWERS_SECTION:start -->/,/<!-- FOLLOWERS_SECTION:end -->/ {next} {print}' README.md > temp.md
          mv temp.md README.md
          cat followers.md >> README.md
          rm followers.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # Pull latest changes before pushing
          git pull origin main --rebase

          git add README.md
          git commit -m "Updated followers list with profile images" || exit 0
          git push origin main
