name: Update Following List

on:
  schedule:
    - cron: "0 0 * * *" # Runs once every day at midnight UTC
  workflow_dispatch: # Allows manual execution

jobs:
  update-following:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Following List
        run: |
          FOLLOWING=$(curl -s https://api.github.com/users/yashKappa/following?per_page=100)

          echo "<!-- FOLLOWING_SECTION:start -->" > following.md
          echo "" >> following.md
          echo "## 🔥 People I Follow" >> following.md
          echo "<div style=\"display: flex; flex-wrap: wrap; justify-content: center; gap: 10px;\">" >> following.md

          COUNT=0
          echo "$FOLLOWING" | jq -r '.[] | "<div style=\"text-align: center; width: 120px;\"><a href=\"https://github.com/\(.login)\"><img src=\"\(.avatar_url)\" width=\"80\" height=\"80\" style=\"border-radius:50%;\"><br>@\(.login)</a></div>"' >> following.md

          while read -r line; do
            if [ $COUNT -eq 0 ]; then
              echo "<tr>" >> following.md
            fi
            
            echo "$line" >> following.md
            COUNT=$((COUNT + 1))

            if [ $COUNT -eq 6 ]; then
              echo "</tr>" >> following.md
              COUNT=0
            fi
          done < raw_following.md

          # Fill empty cells if the last row is incomplete
          if [ $COUNT -gt 0 ]; then
            while [ $COUNT -lt 6 ]; do
              echo "<td></td>" >> following.md
              COUNT=$((COUNT + 1))
            done
            echo "</tr>" >> following.md
          fi

          echo "</div>" >> following.md
          echo "" >> following.md
          echo "<!-- FOLLOWING_SECTION:end -->" >> following.md
          rm raw_following.md

      - name: Update README.md
        run: |
          awk '/<!-- FOLLOWING_SECTION:start -->/,/<!-- FOLLOWING_SECTION:end -->/ {next} {print}' README.md > temp.md
          mv temp.md README.md
          cat following.md >> README.md
          rm following.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/yashKappa/yashKappa.git
          
          # Stash local changes before pulling
          git stash --include-untracked
          
          # Pull latest changes
          git pull origin main --rebase
          
          # Apply stashed changes back
          git stash pop || echo "No stash to apply"
      
          # Add and commit changes
          git add README.md
          git commit -m "Updated followers/following list" || exit 0
          
          # Push changes
          git push origin main
