name: Update Followers List

on:
  schedule:
    - cron: "0 0 * * *" # Runs once every day at midnight UTC
  workflow_dispatch: # Allows manual execution

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Followers List
        run: |
          FOLLOWERS=$(curl -s https://api.github.com/users/yashKappa/followers?per_page=100)

          echo "<!-- FOLLOWERS_SECTION:start -->" > followers.md
          echo "" >> followers.md
          echo "## 🚀 My Followers" >> followers.md
          echo "<div style=\"display: flex; flex-wrap: wrap; gap: 15px;\">" >> followers.md

          echo "$FOLLOWERS" | jq -r '.[] | "<div style=\"text-align: center;\"><a href=\"https://github.com/\(.login)\"><img src=\"\(.avatar_url)\" width=\"80\" height=\"80\" style=\"border-radius:50%;\"><br>@\(.login)</a></div>"' >> followers.md

          echo "</div>" >> followers.md
          echo "" >> followers.md
          echo "<!-- FOLLOWERS_SECTION:end -->" >> followers.md

      - name: Update README.md
        run: |
          awk '/<!-- FOLLOWERS_SECTION:start -->/,/<!-- FOLLOWERS_SECTION:end -->/ {next} {print}' README.md > temp.md
          mv temp.md README.md
          cat followers.md >> README.md
          rm followers.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/yashKappa/yashKappa.git
          
          git add README.md
          git commit -m "Updated followers list" || exit 0
          
          git pull --rebase --autostash origin main || git pull origin main
          git push --force origin main
