name: Update GitHub Followers

on:
  schedule:
    - cron: "*/1 * * * *"  # Runs every minute
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq (JSON Parser)
        run: sudo apt-get install -y jq

      - name: Fetch Followers (Without Authentication)
        run: |
          curl -s "https://api.github.com/users/yashKappa/followers?per_page=10" > followers.json
          
          echo '<h2 align="center">👥 My GitHub Followers</h2>' > followers.md
          echo '<p align="center">' >> followers.md
          jq -r '.[] | "<a href=\"" + .html_url + "\"><img src=\"" + .avatar_url + "\" width=\"50px\" height=\"50px\" style=\"border-radius: 50%; margin: 5px;\"><br>" + .login + "</a>"' followers.json >> followers.md
          echo '</p>' >> followers.md

      - name: Update README
        run: |
          if grep -q "<!-- FOLLOWER_SECTION:start -->" README.md; then
            sed -i '/<!-- FOLLOWER_SECTION:start -->/,/<!-- FOLLOWER_SECTION:end -->/c\<!-- FOLLOWER_SECTION:start -->\n'$(cat followers.md)'\n<!-- FOLLOWER_SECTION:end -->' README.md
          else
            echo "❌ Placeholder not found in README.md!"
            exit 1
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "🔄 Updated followers list" || echo "No changes to commit"
          git push || echo "No changes to push"
