name: Update Followers

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual execution

jobs:
  update-followers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Followers
        run: |
          echo "<!-- FOLLOWER_SECTION:start -->" > followers.md
          echo "" >> followers.md
          echo "| Profile | Profile | Profile | Profile | Profile |" >> followers.md
          echo "|---------|---------|---------|---------|---------|" >> followers.md

          ROW=""
          COUNT=0

          curl -s "https://api.github.com/users/yashKappa/followers?per_page=100" | jq -r '.[] | "| <a href=\"" + .html_url + "\"><img src=\"" + .avatar_url + "\" width=\"50px\" style=\"border-radius:50%;\"></a><br>[@"+ .login +"](" + .html_url + ") "' | while read LINE; do
            ROW="$ROW $LINE"
            COUNT=$((COUNT+1))
            if [ $COUNT -eq 5 ]; then
              echo "$ROW |" >> followers.md
              ROW=""
              COUNT=0
            fi
          done

          if [ $COUNT -ne 0 ]; then
            while [ $COUNT -lt 5 ]; do
              ROW="$ROW |"
              COUNT=$((COUNT+1))
            done
            echo "$ROW" >> followers.md
          fi

          echo "" >> followers.md
          echo "<!-- FOLLOWER_SECTION:end -->" >> followers.md

      - name: Update README.md
        run: |
          awk '/<!-- FOLLOWER_SECTION:start -->/{print;while(getline line < "followers.md") print line;found=1;next} /<!-- FOLLOWER_SECTION:end -->/{found=0} !found' README.md > temp.md
          mv temp.md README.md
          rm followers.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/yashKappa/yashKappa.git
          git add README.md
          git commit -m "🔄 Updated followers list" || echo "No changes to commit"
          git push origin main
