name: Update Followers & Following

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual execution

jobs:
  update-followers-following:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Followers
        run: |
          echo "<!-- FOLLOWER_SECTION:start -->" > followers.md
          echo "" >> followers.md

          curl -s "https://api.github.com/users/yashKappa/followers?per_page=20" |
          jq -r '.[] | "<a href=\"" + .html_url + "\"><img src=\"" + .avatar_url + "\" width=\"50px\" style=\"border-radius:50%; margin:5px;\"><br>" + .login + "</a>&nbsp;&nbsp;"' >> followers.md

          echo "" >> followers.md
          echo "<!-- FOLLOWER_SECTION:end -->" >> followers.md

      - name: Fetch Following
        run: |
          echo "<!-- FOLLOWING_SECTION:start -->" > following.md
          echo "" >> following.md

          curl -s "https://api.github.com/users/yashKappa/following?per_page=20" |
          jq -r '.[] | "<a href=\"" + .html_url + "\"><img src=\"" + .avatar_url + "\" width=\"50px\" style=\"border-radius:50%; margin:5px;\"><br>" + .login + "</a>&nbsp;&nbsp;"' >> following.md

          echo "" >> following.md
          echo "<!-- FOLLOWING_SECTION:end -->" >> following.md

      - name: Update README.md
        run: |
          awk '/<!-- FOLLOWER_SECTION:start -->/{print;while(getline line < "followers.md") print line;found=1;next} /<!-- FOLLOWER_SECTION:end -->/{found=0} !found' README.md > temp.md
          mv temp.md README.md

          awk '/<!-- FOLLOWING_SECTION:start -->/{print;while(getline line < "following.md") print line;found=1;next} /<!-- FOLLOWING_SECTION:end -->/{found=0} !found' README.md > temp.md
          mv temp.md README.md

          rm followers.md following.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/yashKappa/yashKappa.git
          git add README.md
          git commit -m "🔄 Updated followers & following lists" || echo "No changes to commit"
          git push origin main
