name: Update Followers

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual execution

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Followers with Profile Images
        run: |
          FOLLOWERS=$(curl -s https://api.github.com/users/yashKappa/followers?per_page=100 | jq -r '.[] | .login')
          echo "<!-- FOLLOWER_SECTION:start -->" > followers.md
          echo "" >> followers.md
          
          for user in $FOLLOWERS; do
            echo "<table><tr>" >> followers.md
            echo "<td><img src='https://github.com/$user.png' width='50' height='50'></td>" >> followers.md
            echo "<td><a href='https://github.com/$user'>@$user</a></td>" >> followers.md
            echo "</tr></table>" >> followers.md
            echo "<br>" >> followers.md
          done
          
          echo "" >> followers.md
          echo "<!-- FOLLOWER_SECTION:end -->" >> followers.md

      - name: Update README.md
        run: |
          awk '/<!-- FOLLOWER_SECTION:start -->/,/<!-- FOLLOWER_SECTION:end -->/ {next} {print}' README.md > temp.md
          mv temp.md README.md
          cat followers.md >> README.md
          rm followers.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/yashKappa/yashKappa.git
          git add README.md
          git commit -m "Updated followers list" || exit 0
          git push origin main
