      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/yashKappa/yashKappa.git

          # Reset any unstaged changes to avoid conflicts
          git reset --hard HEAD
          
          # Pull the latest changes to avoid conflicts
          git pull --rebase origin main || git pull origin main
          
          git add following.md
          git commit -m "Updated following list with profile images in table format" || exit 0
          git push origin main
