name: Update Following List

on:
  schedule:
    - cron: "0 0 * * *" # Runs once every day at midnight UTC
  workflow_dispatch: # Allows manual execution

jobs:
  update-following:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Following List
        run: |
          FOLLOWING=$(curl -s https://api.github.com/users/yashKappa/following?per_page=100)

          echo "<!-- FOLLOWING_SECTION:start -->" > following.md
          echo "" >> following.md
          echo "## 🔥 People I Follow" >> following.md
          echo "<div style=\"display: flex; flex-wrap: wrap; gap: 20px; justify-content: center;\">" >> following.md

          echo "$FOLLOWING" | jq -r '.[] | "<div style=\"text-align: center; width: 100px;\"><a href=\"https://github.com/\(.login)\"><img src=\"\(.avatar_url)\" width=\"80\" height=\"80\" style=\"border-radius:50%;\"><br>@\(.login)</a></div>"' >> following.md

          echo "</div>" >> following.md
          echo "" >> following.md
          echo "<!-- FOLLOWING_SECTION:end -->" >> following.md

      - name: Update README.md
        run: |
          awk '/<!-- FOLLOWING_SECTION:start -->/,/<!-- FOLLOWING_SECTION:end -->/ {next} {print}' README.md > temp.md
          mv temp.md README.md
          cat following.md >> README.md
          rm following.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/yashKappa/yashKappa.git
          
          git stash --include-untracked
          git pull origin main --rebase
          git stash pop || echo "No stash to apply"

          git add README.md
          git commit -m "Updated following list" || exit 0
          git push origin main
