name: Update Following List

on:
  schedule:
    - cron: "0 0 * * *" # Runs once every day at midnight UTC
  workflow_dispatch: # Allows manual execution

jobs:
  update-following:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Following List
        run: |
          FOLLOWING=$(curl -s https://api.github.com/users/yashKappa/following?per_page=100)

          echo "<!-- FOLLOWING_SECTION:start -->" > following.md
          echo "" >> following.md
          echo "## 🔥 People I Follow" >> following.md
          echo "<table>" >> following.md

          COUNT=0
          echo "$FOLLOWING" | jq -r '.[] | "<td align=\"center\"><a href=\"https://github.com/\(.login)\"><img src=\"\(.avatar_url)\" width=\"80\" height=\"80\" style=\"border-radius:50%;\"><br>@\(.login)</a></td>"' > raw_following.md

          while read -r line; do
            if [ $COUNT -eq 0 ]; then
              echo "<tr>" >> following.md
            fi
            
            echo "$line" >> following.md
            COUNT=$((COUNT + 1))

            if [ $COUNT -eq 6 ]; then
              echo "</tr>" >> following.md
              COUNT=0
            fi
          done < raw_following.md

          if [ $COUNT -gt 0 ]; then
            echo "</tr>" >> following.md
          fi

          echo "</table>" >> following.md
          echo "" >> following.md
          echo "<!-- FOLLOWING_SECTION:end -->" >> following.md
          rm raw_following.md

      - name: Update README.md
        run: |
          awk '/<!-- FOLLOWING_SECTION:start -->/,/<!-- FOLLOWING_SECTION:end -->/ {next} {print}' README.md > temp.md
          mv temp.md README.md
          cat following.md >> README.md
          rm following.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/yashKappa/yashKappa.git
          
          git pull --rebase origin main || git pull origin main
          
          git add README.md
          git commit -m "Updated following list" || exit 0
          git push origin main
