name: Update Followers

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual execution

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Followers
        run: |
          FOLLOWERS=$(curl -s https://api.github.com/users/yashKappa/followers?per_page=100 | jq -r '.[].login')
          echo "<!-- FOLLOWER_SECTION:start -->" > followers.md
          for user in $FOLLOWERS; do
            echo "- [@$user](https://github.com/$user)" >> followers.md
          done
          echo "<!-- FOLLOWER_SECTION:end -->" >> followers.md
          
      - name: Update README.md
        run: |
          awk '/<!-- FOLLOWER_SECTION:start -->/{print; system("cat followers.md"); next} /<!-- FOLLOWER_SECTION:end -->/{print; next} 1' README.md > temp.md
          mv temp.md README.md
          rm followers.md

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated followers list" || exit 0
          git push
