name: Update GitHub Following

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every 24 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-following:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install jq (JSON Parser)
        run: sudo apt-get install -y jq

      - name: Fetch Following
        run: |
          curl -s "https://api.github.com/users/yashKappa/following?per_page=10" > following.json
          echo '<p align="center">' > following.md
          cat following.json | jq -r '.[] | "<a href=\"" + .html_url + "\"><img src=\"" + .avatar_url + "\" width=\"50px\" style=\"border-radius: 50%; margin: 5px;\"><br>" + .login + "</a>&nbsp;&nbsp;"' >> following.md
          echo '</p>' >> following.md

      - name: Update README
        run: |
          sed -i '/<!-- FOLLOWING_SECTION:start -->/,/<!-- FOLLOWING_SECTION:end -->/c\<!-- FOLLOWING_SECTION:start -->\n'$(cat following.md)'\n<!-- FOLLOWING_SECTION:end -->' README.md

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated following list" || echo "No changes to commit"
          git push || echo "No changes to push"
