name: Update Followers List

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual execution

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch Followers List with Profile Images
        run: |
          FOLLOWERS=$(curl -s https://api.github.com/users/yashKappa/followers?per_page=100)
          
          echo "<!-- FOLLOWERS_SECTION:start -->" > followers.md
          echo "" >> followers.md
          echo "<table><tr>" >> followers.md

          COUNT=0
          echo "$FOLLOWERS" | jq -r '.[] | "<td align=\"center\"><a href=\"https://github.com/\(.login)\"><img src=\"\(.avatar_url)&s=100\" width=\"80\" height=\"80\"><br>@\(.login)</a></td>"' >> raw_followers.md

          while read -r line; do
            echo "$line" >> followers.md
            COUNT=$((COUNT + 1))
            if [ $COUNT -eq 6 ]; then
              echo "</tr><tr>" >> followers.md
              COUNT=0
            fi
          done < raw_followers.md

          echo "</tr></table>" >> followers.md
          echo "" >> followers.md
          echo "<!-- FOLLOWERS_SECTION:end -->" >> followers.md
          rm raw_followers.md

      - name: Update README.md
        run: |
          awk '/<!-- FOLLOWERS_SECTION:start -->/,/<!-- FOLLOWERS_SECTION:end -->/ {next} {print}' README.md > temp.md
          mv temp.md README.md
          cat followers.md >> README.md
          rm followers.md

      - name: Commit & Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/yashKappa/yashKappa.git
          git add README.md
          git commit -m "Updated followers list with profile images in table format" || exit 0
          git push origin main
